  - name: Check pip3 install
    shell: /usr/local/bin/pip3 --version
    register: pip_install
    check_mode: no
    become_user: root
    become_method: sudo

  - name: get get-pip.py
    become_user: root
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: "/root/get-pip.py"
      timeout: 120
    register: get_url_result

  - name: Install pip
    shell: "chdir=/root /bin/python3 get-pip.py"
    when: pip_install.stdout.find("from /usr/lib/python3.6/site-packages (python 3.6)") == -1

  - name: pip3 install packages
    shell: "source /home/{{ django_worker_user }}/aa_env/bin/activate; pip install torch torchvision scipy"
    check_mode: no
    become_user: root
    become_method: sudo

  - name: install packages
    shell: "/usr/local/bin/pip install torch torchvision scipy"
    check_mode: no
    become_user: root
    become_method: sudo

  - name: clone DMPfold
    git:
      repo: https://github.com/psipred/DMPfold.git
      dest: /data/DMPfold
      clone: yes
      force: yes

  - name: copy over CNS
    become_user: root
    become_method: sudo
    copy:
      src: secrets/cns_solve_1.3_all.tar.gz
      dest: /data/cns_solve_1.3_all.tar.gz
      mode: "uog+x"

  - name: untar cns
    shell: "chdir=/data tar -zxvf cns_solve_1.3_all.tar.gz"

  - name: copy over readdata
    become_user: root
    become_method: sudo
    copy:
      src: files/readdata
      dest: /data/cns_solve_1.3/modules/nmr/readdata
      mode: "uog+x"

  - name: Install flex-devel
    yum:
      pkg: flex-devel
      state: latest
    become_user: root

  - name: copy over .cns_solve_env_sh
    become_user: root
    become_method: sudo
    copy:
      src: files/.cns_solve_env_sh
      dest: /data/cns_solve_1.3/.cns_solve_env_sh
      mode: "uog+x"

  - name: copy over machvar.inc
    become_user: root
    become_method: sudo
    copy:
      src: files/machvar.inc
      dest: /data/cns_solve_1.3/source/machvar.inc
      mode: "uog+x"

  - name: copy over machvar.f
    become_user: root
    become_method: sudo
    copy:
      src: files/machvar.f
      dest: /data/cns_solve_1.3/source/machvar.f
      mode: "uog+x"

  - name: copy over rtf.inc
    become_user: root
    become_method: sudo
    copy:
      src: files/rtf.inc
      dest: /opt/cns_solve_1.3/source/rtf.inc
      mode: "uog+x"

  - name: install CNS
    shell: "chdir=/data/cns_solve_1.3 make install"
    become_user: root

  - name: copy over Makefile
    become_user: root
    become_method: sudo
    copy:
      src: files/Makefile
      dest: /data/cns_solve_1.3/intel-x86_64bit-linux/source/Makefile
      mode: "uog+x"

  - name: install CNS
    shell: "chdir=/data/cns_solve_1.3/intel-x86_64bit-linux/source make install"
    become_user: root

  - name: patch files
    shell: "chdir=/data/DMPfold/cnsfiles sh installscripts.sh"
    become_user: root

  - name: make DMPfold
    shell: "chdir=/data/DMPfold/src make"

  - name: install CNS
    shell: "chdir=/data/DMPfold/src make install"
    become_user: root

  - name: copy over seq2maps
    become_user: root
    become_method: sudo
    copy:
      src: files/seq2maps.csh
      dest: /data/DMPfold/seq2maps.csh
      mode: "uog+x"

  - name: copy over aln2maps
    become_user: root
    become_method: sudo
    copy:
      src: files/aln2maps.csh
      dest: /opt/DMPfold/aln2maps.csh
      mode: "uog+x"

  - name: copy over runpsipredandsolvwithdb
    become_user: root
    become_method: sudo
    copy:
      src: files/runpsipredandsolvwithdb
      dest: /opt/DMPfold/bin/runpsipredandsolvwithdb
      mode: "uog+x"

  - name: copy over rundmpfold.sh
    become_user: root
    become_method: sudo
    copy:
      src: files/run_dmpfold.sh
      dest: /opt/DMPfold/run_dmpfold.sh
      mode: "uog+x"
