---
# ansible-playbook -i staging deploy_staging.yml -f 1
#
#  WARNING! YOU MUST HAVE A COMPLETE secrets/
#  YOU MUST HAVE files/jdk-8u60-linux-x64.tar.gz
#

# NOT NEEDED IN PRODUCTION
# - name: Set up common bits needed for the rest of the install
#   hosts: everyone
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - common
#   vars_files:
#     - secrets/production_secrets.yaml

# - name: Apply the redis configuration
#   hosts: redis
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#    - redis
#   vars_files:
#    - secrets/production_secrets.yaml

# - name: Apply the postgres configuration
#   hosts: dbserver
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - dbserver
#   vars_files:
#     - secrets/production_secrets.yaml
# # #
# - name: Apply Analytics Automated head node configuration
#   hosts: aa_head
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - aahead
#   vars_files:
#     - secrets/production_secrets.yaml

# - name: Create blastmachine
#   hosts: blastmachine
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - blastworkers
#     # - blastmachine
#   vars_files:
#     - secrets/production_secrets.yaml
#
# - name: Create blast_cache machine
#   hosts: blast_cache
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     - djangomachine
#     - blastcache
#   vars_files:
#     - secrets/production_secrets.yaml

# mempack won't compile in OSX
# domThreader seg faults in OSX
#
# - name: Create Celery worker node
#   hosts: celery_worker_node
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - aaworker
#     # - psipred
#     # - disopred
#     # - memsatsvm
#     # - pGenTHREADER
#     # - model_parts # get the bits for the frontend simple modelling
#     # - dompred
#     # - mempack
#     # - bioserf
#     # - ffpred
#     #- metapsicov
#     # - metsite
#     # - hspred
#     # - memembed
#     # - maketdb
#   vars_files:
#     - secrets/production_secrets.yaml

# - name: Install webserver
#   hosts: webserver
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - webserver
#   vars_files:
#     - secrets/production_secrets.yaml

# - name: Updates for datanodes
#   hosts: update_data
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     - dataupdates
#   vars_files:
#     - secrets/staging_secrets.yaml
#
# - name: Updates for blastnodes
#   hosts: update_blast
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     - blastupdates
#   vars_files:
#     - secrets/staging_secrets.yaml

- name: Tidy processing tmp
  hosts: clear_tmp
  become: true
  become_user: root
  become_method: sudo
  roles:
    - cleartmp
  vars_files:
    - secrets/production_secrets.yaml

- name: Tidy old db entries
  hosts: clear_db
  become: true
  become_user: root
  become_method: sudo
  roles:
    - cleardb
  vars_files:
    - secrets/production_secrets.yaml
