  - name: Update core packages
    yum:
      name:
        - boost
        - boost-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Check memembed is present
    stat: path=/data/memembed
    register: memembed_exist

  - name : Check out memembed from GIT
    when: memembed_exist.stat.exists == False
    git:
      repo: https://github.com/psipred/memembed.git
      dest: /data/memembed
      clone: yes
      force: yes

  - name: make and install memembed
    shell: "cd /data/memembed; make"
    when: memembed_exist.stat.exists == False
