---

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    check_mode: no
    become_user: root
    become_method: sudo

  - name: Add http firewalld rules
    command: firewall-cmd --zone=public --add-service=http --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Enable firewalld port forwarding
    command: firewall-cmd --zone=public --add-masquerade --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 80 to 8000
    command: firewall-cmd --zone=public --add-forward-port=port=80:proto=tcp:toport=8000 --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 443 to 4433
    command: firewall-cmd --zone=public --add-forward-port=port=443:proto=tcp:toport=4433 --permanent
    become_user: root
    become_method: sudo

    when: firewalldrules.stdout.find("http") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    become_user: root
    become_method: sudo

  - name: Install Python 3
    yum:
      pkg: python34
      state: latest
    become_user: root
    become_method: sudo

  - name: Install Python-devel
    yum:
      pkg: python-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Install Python34-devel
    yum:
      pkg: python34-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Install VirtualEnv
    yum:
      pkg: python-virtualenv
      state: latest
    become_user: root
    become_method: sudo

  - name: Install virtualenvwrapper
    yum:
      pkg: python-virtualenvwrapper
      state: latest
    become_user: root
    become_method: sudo

  - name: Install R
    yum:
      pkg: R-core.x86_64, R-core-devel.x86_64, R-devel.x86_64
      state: latest
    become_user: root
    become_method: sudo

  - name: Install blas/lapack
    yum:
      pkg: blas, lapack, blas-devel, lapack-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Ensure group "apache" exists
    group:
      name: apache
      state: present
    become_user: root
    become_method: sudo
