  - name: Install epel
    yum:
      pkg: epel-release
      state: latest
    become_user: root
    become_method: sudo

  - name: get nux gpg-key
    shell: rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    become_user: root
    become_method: sudo

  - name: Add nux repo
    shell: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    become_user: root
    become_method: sudo
    ignore_errors: True

  - name: Update core packages
    yum:
      name:
        - git
        - nss
        - curl
        - libcurl
        - python34
        - python-psycopg2
        - libpqxx
        - postgresql-devel
        - httpd
        - httpd-devel
        - mod_wsgi
        - readline-devel
        - perl-CPAN
        - perl-App-cpanminus.noarch
      state: latest
    become_user: root
    become_method: sudo

  - name: Check pip install
    shell: pip --version
    register: pip_install
    check_mode: no
    ignore_errors: yes
    become_user: root
    become_method: sudo

  # - name: Download get-pip.py
  #   shell: "chdir={{ webserver_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
  #   become_user: "{{ webserver_user }}"
  #   register: get_url_result
  #   until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
  #   retries: 2
  #   delay: 10
  #   when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  - name: get get-pip.py
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: "/root/get-pip.py"
      timeout: 120
    register: get_url_result
    become_user: root
    become_method: sudo

  - name: Install pip
    shell: "chdir=/root /bin/python3.4 get-pip.py"
    when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1
    become_user: root
    become_method: sudo

  - pip:
      name: psycopg2
    become_user: root
    become_method: sudo
