  - name: Install epel
    yum:
      pkg: epel-release
      state: latest
    become_user: root
    become_method: sudo

  - name: get nux gpg-key
    shell: rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    become_user: root
    become_method: sudo

  - name: Add nux repo
    shell: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    become_user: root
    become_method: sudo
    ignore_errors: True

  - name: Update core packages
    yum:
      name:
        - git
        - nss
        - curl
        - libcurl
        - python36
        - python-psycopg2
        - libpqxx
        - postgresql-devel
        - httpd
        - httpd-devel
        - mod_wsgi
        - readline-devel
        - perl-CPAN
        - perl-App-cpanminus.noarch
        - wget
      state: latest
    become_user: root
    become_method: sudo

  - name: Check pip install
    shell: pip --version
    register: pip_install
    check_mode: no
    ignore_errors: yes
    become_user: root
    become_method: sudo

  # - name: Download get-pip.py
  #   shell: "chdir={{ webserver_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
  #   become_user: "{{ webserver_user }}"
  #   register: get_url_result
  #   until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
  #   retries: 2
  #   delay: 10
  #   when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1
  #
  # - name: get get-pip.py
  #   get_url:
  #     url: https://bootstrap.pypa.io/get-pip.py
  #     dest: "/root/get-pip.py"
  #     timeout: 120
  #   register: get_url_result
  #   become_user: root
  #   become_method: sudo
  #
  # - name: Install pip
  #   shell: "chdir=/root /bin/python3.4 get-pip.py"
  #   when: pip_install.stdout.find("from /usr/lib/python3.6/site-packages (python 3.6)") == -1
  #   become_user: root
  #   become_method: sudo
  #
  # - pip:
  #     name: psycopg2
  #   become_user: root
  #   become_method: sudo

  - name: add data to yum.conf
    become_user: root
    lineinfile:
      path: /etc/yum.conf
      insertafter: 'distroverpkg=centos-release\n'
      line: 'exclude=redis git nss curl libcurl python3* python-psycopg2 libpqxx postgresql-devel httpd httpd-devel mod_wsgi readline-devel perl-CPAN perl-App-cpanminus.noarch wget java java-1.8.0-openjdk python36-devel R-core.x86_64 R-core-devel.x86_64 R-devel.x86_64 blas lapack  blas-devel lapack-devel gnuplot glibc.i686 tcsh compat-libf2c-34.x86 boost boost-devel_64 gd gd-devel lapack64 lapack64-devel openblas-devel glib2-2.56.1-2.el7.i686 ruby ffmpeg ffmpeg-devel lmdb ghostscript ghostscript-devel'
