  - name: Install epel
    yum:
      pkg: glib2-2.56.1-2.el7.i686
      state: latest
    become_user: root
    become_method: sudo


  - name: Check simple_modeller exists
    stat: path=/data/simple_modeller
    register: simple_modeller_exist

  - name: Check out simple_modeller
    when: simple_modeller_exist.stat.exists == False
    git:
      repo: https://github.com/psipred/simple_modeller.git
      dest: /data/simple_modeller
      clone: yes
      force: yes

  - name: install requests
    when: simple_modeller_exist.stat.exists == False
    shell: pip install requests

  - name: Check PDB dir exists
    stat: path=/data/pdb/
    register: pdb_path_exist

  - name: make PDB dir
    when: pdb_path_exist.stat.exists == False
    file:
      path: /data/pdb
      state: directory
      mode: 0666
      recurse: yes

  # - name: rsync the PDB
  #   shell: "cd /data/pdb; rsync -rlpt -v -z --delete rsync.ebi.ac.uk::pub/databases/msd/pdb_uncompressed/ /data/pdb/"

  - name: wget the PDB
    shell: "cd /data/pdb; rsync -rlpt -v -z --delete --copy-links --port=33444 rsync.rcsb.org::ftp_data/structures/all/pdb/ ./"

  - name: set owner to django_worker
    shell: chown -R django_worker /data/pdb/

  - name: set owner to django_worker
    shell: cd /data/pdb; find . -maxdepth 1 -not -name "." -print0 | xargs --null chown -R django_worker
