  - name: Check metsite is present
    stat: path=/data/metsite
    register: metsite_exist

  - name : Check out metsite from GIT
    when: metsite_exist.stat.exists == False
    git:
      repo: https://github.com/psipred/metsite.git
      dest: /data/metsite
      clone: yes
      force: yes

  - name: make metsite components
    when: metsite_exist.stat.exists == False
    shell: "cd /data/metsite/src/; make"

  - name: install metsite
    when: metsite_exist.stat.exists == False
    shell: "cd /data/metsite/src; make install"
